027xiguapi/pear-rec

- LICENSE
- package.json
- packages/desktop/electron/preload/loading.ts
- packages/desktop/package.json
- packages/desktop/tsconfig.build.json
- packages/desktop/tsconfig.json
- packages/desktop/tsconfig.node.json
- packages/docs/.vitepress/config.ts
- packages/docs/md/qrcode-examples.md
- packages/docs/package.json
- packages/recorder/package.json
- packages/screenshot/package.json
- packages/screenshot/src/Screenshots/operations/Scan/index.tsx
- packages/screenshot/tsconfig.json
- packages/timer/package.json
- packages/web/package.json
- packages/web/src/components/card/recordScreenCard.tsx
- packages/web/src/components/card/viewAudioCard.tsx
- packages/web/src/components/card/viewImageCard.tsx
- packages/web/src/components/card/viewVideoCard.tsx
- packages/web/src/pages/clipScreen/index.tsx
- packages/web/src/pages/editImage/index.tsx
- packages/web/src/pages/shotScreen/index.tsx
- packages/web/src/pages/viewVideo/index.tsx
> docs: 修改开源协议

- README.md
- README.zh-CN.md
- packages/desktop/.env
- packages/desktop/electron/main/contract.ts
- packages/desktop/package.json
- packages/desktop/vite.config.ts
- packages/server/lib/util/index.ts
- packages/server/package.json
- packages/web/src/pages/.env
- packages/web/src/pages/viewImage/index.tsx
- packages/web/src/pages/viewVideo/index.module.scss
- packages/web/src/pages/viewVideo/index.tsx
> feat: 多视频预览

- README.md
- README.zh-CN.md
- packages/server/src/api/local.ts
- packages/server/src/util/index.ts
- packages/web/src/components/card/recordAudioCard.tsx
- packages/web/src/components/card/recordScreenCard.tsx
- packages/web/src/components/card/recordVideoCard.tsx
- packages/web/src/components/card/shotScreenCard.tsx
- packages/web/src/components/card/viewAudioCard.tsx
- packages/web/src/components/card/viewImageCard.tsx
- packages/web/src/components/card/viewVideoCard.tsx
- packages/web/src/pages/home/index.module.scss
> refactor: 视频流播放，主页样式调整

- packages/web/src/components/card/viewAudioCard.tsx
- packages/web/src/components/card/viewImageCard.tsx
- packages/web/src/components/card/viewVideoCard.tsx
- packages/web/src/components/recorderAudio/AudioRecorder.tsx
- packages/web/src/components/recorderAudio/WaveSurferPlayer.tsx
- packages/web/src/components/upload/UploadAudio.tsx
- packages/web/src/pages/index.scss
- packages/web/src/pages/recorderAudio/index.tsx
> feat: 本地音频预览、删除音频记录

- packages/recorder/src/main.ts
- packages/web/package.json
- packages/web/src/components/recorderAudio/WaveSurferPlayer.tsx
- packages/web/src/components/recorderScreen/CropArea.tsx
- packages/web/src/components/recorderScreen/CropRecorder.tsx
- packages/web/src/components/recorderScreen/MuteRecorder.tsx
- packages/web/src/components/recorderScreen/PauseRecorder.tsx
- packages/web/src/components/recorderScreen/PlayRecorder.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/components/recorderScreen/SelectMedia.tsx
- packages/web/src/components/recorderScreen/StopRecorder.tsx
- packages/web/src/components/setting/basicSetting.tsx
- packages/web/src/components/upload/UploadImg.tsx
- packages/web/src/pages/recorderAudio/index.module.scss
- packages/web/src/pages/recorderScreen/index copy.tsx
- packages/web/src/pages/recorderScreen/index.module copy.scss
- packages/web/src/pages/recorderScreen/index.module.scss
- packages/web/src/pages/recorderScreen/index.tsx
- packages/web/src/pages/shotScreen/index.tsx
> feat: web 区域录屏

- packages/web/src/components/card/recordScreenCard.tsx
- packages/web/src/components/recorderScreen/CropArea.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/pages/recorderScreen/index.module.scss
> perf: 优化录屏

- packages/desktop/electron/win/recorderAudioWin.ts
- packages/web/src/components/recorderAudio/AudioRecorder.tsx
- packages/web/src/components/recorderScreen/MuteRecorder.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/pages/recorderScreen/index.module.scss
> feat: 录屏增加计时

- packages/desktop/electron/electron-env.d.ts
- packages/desktop/electron/main/index.ts
- packages/desktop/electron/win/recorderAudioWin.ts
- packages/server/rollup.config.mjs
- packages/server/src/index.ts
- packages/server/src/server.ts
- packages/web/src/components/recorderAudio/AudioRecorder.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/pages/recorderAudio/index.module.scss
- packages/web/src/pages/recorderScreen/index.module.scss
- packages/web/src/pages/recorderScreen/index.tsx
- packages/web/src/pages/shotScreen/index.tsx
- packages/web/vite.config.ts
> fix: web和desktop联调修改bug

- packages/desktop/electron/win/viewVideoWin.ts
- packages/server/src/api/local.ts
- packages/server/src/util/index.ts
- packages/web/src/components/card/viewVideoCard.tsx
- packages/web/src/components/recorderAudio/WaveSurferPlayer.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/pages/home/index.tsx
- packages/web/src/pages/index.scss
- packages/web/src/pages/main.tsx
- packages/web/src/pages/recorderAudio/index.tsx
- packages/web/src/pages/recorderScreen/index copy.tsx
- packages/web/src/pages/recorderScreen/index.tsx
- packages/web/src/pages/recorderVideo/index.tsx
- packages/web/src/pages/setting/index.tsx
- packages/web/src/pages/shotScreen/index.tsx
- packages/web/src/pages/viewImage/index.tsx
- packages/web/src/pages/viewVideo/index.tsx
> perf: 统一下载、优化获取用户

- package.json
- packages/desktop/CHANGELOG.md
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/desktop/package.json
- patches/fluent-ffmpeg@2.1.2.patch
> fix: fluent-ffmpeg引入bug

- packages/desktop/CHANGELOG.md
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/desktop/package.json
- packages/web/src/components/card/viewVideoCard.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
> fix: 录屏下载bug

- package.json
- packages/desktop/electron/main/globalShortcut.ts
- packages/desktop/electron/main/index.ts
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/server/src/api/local.ts
- packages/server/src/controller/RecordController.ts
- packages/server/src/controller/SettingController.ts
- packages/server/src/controller/UserController.ts
- packages/server/src/util/index.ts
- packages/web/CHANGELOG.md
- packages/web/package.json
- packages/web/src/components/setting/basicSetting.tsx
- packages/web/src/util/request.ts
> fix: 设置初始化 bug

- .gitignore
- packages/desktop/.env
- packages/desktop/CHANGELOG.md
- packages/desktop/electron/win/editImageWin.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/server/src/contract/index.ts
- packages/server/src/controller/SettingController.ts
- packages/server/src/util/index.ts
- packages/web/CHANGELOG.md
- packages/web/src/components/setting/serverSetting.tsx
- packages/web/src/pages/.env
- packages/web/src/pages/recorderVideo/index.tsx
- packages/web/vite.config.ts
fix: 录像下载 、electron 修改图片加载 bug, perf: 修改端口
> fix: 录像下载 、electron 修改图片加载 bug, perf: 修改端口

- README.md
- README.zh-CN.md
- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/server/src/api/local.ts
- packages/server/src/controller/RecordController.ts
- packages/server/src/route/Record.ts
- packages/web/CHANGELOG.md
- packages/web/package.json
- packages/web/src/api/index.ts
- packages/web/src/api/record.ts
- packages/web/src/components/records/RecordsContent.tsx
- packages/web/src/components/records/RecordsHeader.tsx
- packages/web/src/pages/records.html
- packages/web/src/pages/records/index.module.scss
- packages/web/src/pages/records/index.tsx
- packages/web/src/util/bus.ts
- tools/release.ts
> feat: 增加记录

- packages/desktop/CHANGELOG.md
- packages/desktop/electron-builder.json5
- packages/desktop/electron/main/globalShortcut.ts
- packages/desktop/electron/main/tray.ts
- packages/desktop/electron/win/shotScreenWin.ts
- packages/desktop/package.json
> feat: 设置快捷键

- README.de-DE.md
- README.md
- README.zh-CN.md
- packages/desktop/CHANGELOG.md
- packages/desktop/electron-builder.json5
- packages/desktop/electron/win/clipScreenWin.ts
- packages/desktop/electron/win/recorderFullScreenWin.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/desktop/package.json
- packages/server/rollup.config.mjs
- packages/timer/src/Timer/digit/index.module.scss
- packages/web/CHANGELOG.md
- packages/web/src/components/card/recordScreenCard.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/components/recorderScreen/worker.js
> fix: 录屏 bug

- packages/desktop/electron/main/serverProcess.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/viewVideoWin.ts
- packages/server/CHANGELOG.md
- packages/server/src/app/app.service.ts
- packages/server/src/app/file.controller.ts
- packages/server/src/config/index.ts
- packages/server/src/records/dto/create-record.dto.ts
- packages/server/src/records/entity/record.entity.ts
- packages/server/src/settings/entity/setting.entity.ts
- packages/server/src/settings/settings.controller.ts
- packages/server/src/settings/settings.module.ts
- packages/server/src/settings/settings.service.ts
- packages/server/src/users/entity/user.entity.ts
- packages/server/src/users/users.service.ts
- packages/web/src/api/setting.ts
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
> fix: 配置初始 bug

- packages/server/CHANGELOG.md
- packages/server/package.json
- packages/server/src/config/index.ts
- packages/server/src/records/records.service.ts
- packages/server/src/settings/settings.controller.ts
- packages/server/src/settings/settings.module.ts
- packages/server/src/settings/settings.service.ts
- packages/server/src/users/dto/create-user.dto.ts
- packages/server/src/users/entity/user.entity.ts
- packages/web/CHANGELOG.md
- packages/web/package.json
- packages/web/src/components/records/RecordsContent.tsx
- packages/web/src/components/videoToGif/VideoToGifConverter.tsx
- packages/web/src/pages/editImage/index.tsx
- packages/web/src/pages/pinImage/index.tsx
> fix: 修改图片和钉图打不开bug、创建设置bug

- packages/desktop/CHANGELOG.md
- packages/desktop/electron/main/contract.ts
- packages/desktop/electron/main/index.ts
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/main/logger.ts
- packages/desktop/electron/main/serverProcess.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/viewImageWin.ts
- packages/desktop/package.json
- packages/web/src/components/editGif/VideoToGifConverter.tsx
> feat: 增加日志

- packages/screenshot/src/Screenshots/ScreenshotsContext.ts
- packages/server/src/app/app.service.ts
- packages/server/src/app/file.controller.ts
- packages/web/src/api/index.ts
- packages/web/src/components/context/GifContext.tsx
- packages/web/src/components/context/UserContext.tsx
- packages/web/src/components/editGif/GifConverter.tsx
- packages/web/src/components/editGif/tool/File.tsx
- packages/web/src/components/editGif/tool/Play.tsx
- packages/web/src/components/editGif/tool/file.module.scss
- packages/web/src/components/editGif/tool/play.module.scss
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/components/recorderScreen/worker.js
- packages/web/src/pages/editGif/index.module.scss
- packages/web/src/pages/editGif/index.tsx
> feat: 编辑动图优化

- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/i18n/locales/zh-CN.json
- packages/web/src/pages/home/index.module.scss
- packages/web/src/pages/home/index.tsx
- packages/web/src/pages/index.scss
> feat: 首页增加波浪背景

- packages/desktop/electron/win/mainWin.ts
- packages/desktop/package.json
- packages/web/src/components/home/HomeFooter.tsx
- packages/web/src/components/update/index.tsx
- packages/web/src/pages/home/index.module.scss
- packages/web/src/pages/home/index.tsx
- packages/web/src/pages/index.scss
> perf: 优化软件更新

- .npmrc
- README.de-DE.md
- README.md
- README.zh-CN.md
- package.json
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/win/shotScreenWin.ts
- packages/desktop/package.json
- packages/server/package.json
- packages/server/webpack.config.js
- packages/web/package.json
#60 macos无法截屏 bug 解决
#75 服务打包 bug 解决
> fix: macos无法截屏、服务打包 bug

- packages/desktop/electron/preload/index.ts
- packages/desktop/electron/win/clipScreenWin.ts
- packages/desktop/electron/win/mainWin.ts
- packages/web/src/pages/main.tsx
> feat: 增加页面loading

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/pinImageWin.ts
- packages/web/src/components/card/viewImageCard.tsx
- packages/web/src/components/common/header/index.module.scss
- packages/web/src/components/common/header/index.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/components/recorderScreen/SelectMedia.tsx
- packages/web/src/pages/pinImage/index.module.scss
- packages/web/src/pages/pinImage/index.tsx
- packages/web/src/pages/recorderFullScreen/index.tsx
> perf: 钉图优化

- packages/desktop/package.json
- packages/web/src/components/context/GifContext.tsx
- packages/web/src/components/context/HistoryContext.tsx
- packages/web/src/components/editGif/GifConverter.tsx
- packages/web/src/components/editGif/tool/Frame.tsx
- packages/web/src/components/editGif/tool/History.tsx
- packages/web/src/components/editGif/tool/Play.tsx
- packages/web/src/components/editGif/tool/history.module.scss
- packages/web/src/components/home/HomeFooter.tsx
- packages/web/src/components/setting/userSetting.tsx
- packages/web/src/pages/editGif/index.module.scss
- packages/web/src/pages/editGif/index.tsx
> feat: 动图实现历史功能

- README.md
- README.zh-CN.md
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/preload/index.ts
- packages/desktop/electron/win/pinVideoWin.ts
- packages/web/src/components/card/viewVideoCard.tsx
- packages/web/src/pages/pinImage/index.tsx
- packages/web/src/pages/pinVideo.html
- packages/web/src/pages/pinVideo/index.module.scss
- packages/web/src/pages/pinVideo/index.tsx
- packages/web/src/pages/recorderFullScreen/index.tsx
> feat: 录全屏增加摄像头

- packages/web/src/pages/recorderFullScreen/index.tsx
> fix: 录全屏时没有声音

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/spliceImageWin.ts
- packages/web/src/components/card/viewImageCard.tsx
- packages/web/src/components/editGif/tool/Setting.tsx
- packages/web/src/components/editGif/tool/Splice.tsx
- packages/web/src/components/spliceImg/index.tsx
- packages/web/src/components/spliceImg/spliceImg.module.scss
- packages/web/src/components/spliceImg/upload.tsx
- packages/web/src/pages/spliceImage/index.tsx
> feat: 新增拼接图片页面

- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
> fix: 录屏有黑边 bug

- packages/desktop/electron/main/constant.ts
- packages/desktop/electron/win/canvasWin.ts
- packages/desktop/electron/win/clipScreenWin.ts
- packages/desktop/electron/win/editGifWin.ts
- packages/desktop/electron/win/editImageWin.ts
- packages/desktop/electron/win/mainWin.ts
- packages/desktop/electron/win/pinImageWin.ts
- packages/desktop/electron/win/pinVideoWin.ts
- packages/desktop/electron/win/recorderAudioWin.ts
- packages/desktop/electron/win/recorderFullScreenWin.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/desktop/electron/win/recorderVideoWin.ts
- packages/desktop/electron/win/recordsWin.ts
- packages/desktop/electron/win/settingWin.ts
- packages/desktop/electron/win/shotScreenWin.ts
- packages/desktop/electron/win/spliceImageWin.ts
- packages/desktop/electron/win/viewAudioWin.ts
- packages/desktop/electron/win/viewImageWin.ts
- packages/desktop/electron/win/viewVideoWin.ts
> perf: 优化配置

- packages/desktop/electron/main/constant.ts
- packages/desktop/electron/win/recorderFullScreenWin.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/pages/recorderAudio/index.tsx
- packages/web/src/pages/recorderFullScreen/index.tsx
[electron录制窗口+系统声音和麦克风声音](https://segmentfault.com/q/1010000019685388)
#115
参考 https://segmentfault.com/q/1010000019685388
> fix: 录屏获取系统声音

- packages/web/src/db/index.ts
- packages/web/src/vite-env.d.ts
- packages/web/vite.config.ts
> fix: PWA无法缓存html后面带参数的页面

- packages/desktop/package.json
- packages/web/CHANGELOG.md
- packages/web/package.json
- packages/web/public/js/tongji.js
- packages/web/src/pages/canvas.html
- packages/web/src/pages/clipScreen.html
- packages/web/src/pages/editGif.html
- packages/web/src/pages/editImage.html
- packages/web/src/pages/index.html
- packages/web/src/pages/pinImage.html
- packages/web/src/pages/pinVideo.html
- packages/web/src/pages/recorderAudio.html
- packages/web/src/pages/recorderFullScreen.html
- packages/web/src/pages/recorderScreen.html
- packages/web/src/pages/recorderVideo.html
- packages/web/src/pages/records.html
- packages/web/src/pages/setting.html
- packages/web/src/pages/shotScreen.html
- packages/web/src/pages/spliceImage.html
- packages/web/src/pages/viewAudio.html
- packages/web/src/pages/viewImage.html
- packages/web/src/pages/viewVideo.html
> feat: 网站统计

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/web/CHANGELOG.md
- packages/web/src/components/common/header/index.module.scss
- packages/web/src/components/common/header/index.tsx
- packages/web/src/components/setting/basicSetting.tsx
- packages/web/src/components/setting/userSetting.tsx
- packages/web/src/pages/viewImage/index.tsx
> fix: 开机自启动 bug、图片预览钉图 bug

- packages/desktop/CHANGELOG.md
- packages/desktop/electron/main/constant.ts
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/videoConverterWin.ts
- packages/desktop/package.json
- packages/web/src/components/setting/userSetting.tsx
- packages/web/src/components/videoToGif/index.module.scss
- packages/web/src/components/videoToGif/index.tsx
- packages/web/src/pages/home/index.module.scss
- packages/web/src/pages/videoConverter.html
- packages/web/src/pages/videoConverter/index.module.scss
- packages/web/src/pages/videoConverter/index.tsx
- packages/web/vite.config.ts
> feat: 增加视频转换

- README.md
- packages/desktop/.env
- packages/desktop/electron/main/app.ts
- packages/desktop/electron/main/index.ts
- packages/desktop/electron/main/protocol.ts
- packages/web/src/pages/editGif/index.tsx
- packages/web/src/pages/home/index.module.scss
- packages/web/src/pages/pinImage/index.tsx
- packages/web/src/pages/viewAudio/index.tsx
- packages/web/src/pages/viewVideo/index.tsx
- packages/web/src/util/searchImg/baidu.ts
> fix: 以图搜图 bug

- README.md
- README.zh-CN.md
- package.json
- packages/web/src/pages/home/index.module.scss
> perf: 优化首页样式

- packages/desktop/electron/main/globalShortcut.ts
- packages/desktop/electron/main/index.ts
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/main/tray.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/package.json
- packages/web/src/components/setting/shortcutSetting.tsx
- packages/web/src/components/setting/userSetting.tsx
- packages/web/src/db/index.ts
- packages/web/src/db/shortcut.ts
- packages/web/src/pages/home/index.module.scss
- packages/web/src/pages/home/index.tsx
- packages/web/src/pages/main.tsx
- packages/web/src/vite-env.d.ts
> feat: 自定义快捷键

- README.md
- README.zh-CN.md
- packages/desktop/electron/i18n/de-DE.json
- packages/desktop/electron/i18n/en-US.json
- packages/desktop/electron/i18n/zh-CN.json
- packages/web/src/components/card/recordCanvasCard.tsx
- packages/web/src/components/common/header/index.module.scss
- packages/web/src/components/common/header/index.tsx
- packages/web/src/components/setting/shortcutSetting.tsx
- packages/web/src/i18n/locales/de-DE.json
- packages/web/src/i18n/locales/en-US.json
- packages/web/src/i18n/locales/zh-CN.json
- packages/web/src/pages/home/index.tsx
feat: 查看图片国际化;
feat: 首页增加编辑图片和画板卡片;
> feat: 查看图片国际化; feat: 首页增加编辑图片和画板卡片;

- packages/desktop/electron/main/globalShortcut.ts
- packages/desktop/electron/main/index.ts
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/main/tray.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/mainWin.ts
- packages/desktop/electron/win/shotScreenWin.ts
- packages/web/src/components/card/shotScreenCard.tsx
- packages/web/src/components/common/header/index.tsx
- packages/web/src/pages/shotScreen/index.tsx
> perf: 优化截图

- packages/desktop/electron/preload/index.ts
- packages/web/src/pages/home/index.module.scss
- packages/web/src/pages/home/index.tsx
- packages/web/src/pages/index.scss
> feat: 增加首页骨架屏

- packages/desktop/electron/main/constant.ts
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/win/clipScreenWin.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/timer/src/Timer/index.module.scss
- packages/timer/src/Timer/index.tsx
- packages/web/src/components/recorderScreen/MuteRecorder.tsx
- packages/web/src/components/recorderScreen/PauseRecorder.tsx
- packages/web/src/components/recorderScreen/PlayRecorder.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/components/recorderScreen/ShotScreen.tsx
- packages/web/src/components/recorderScreen/StopRecorder.tsx
- packages/web/src/pages/clipScreen/index.module.scss
- packages/web/src/pages/clipScreen/index.tsx
- packages/web/src/pages/recorderScreen/index.module.scss
> perf: 重构录屏

- README.zh-CN.md
- packages/desktop/electron/i18n/zh-CN.json
- packages/desktop/electron/main/constant.ts
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/main/notification.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/preload/index.ts
- packages/desktop/electron/win/clipScreenWin.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/desktop/electron/win/shotScreenWin.ts
- packages/docs/desktop/examples.md
- packages/web/package.json
- packages/web/src/components/recorderScreen/FullScreen.tsx
- packages/web/src/components/recorderScreen/MicMuteRecorder.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/components/recorderScreen/SoundMuteRecorder.tsx
- packages/web/src/i18n/locales/zh-CN.json
- packages/web/src/pages/index.scss
- packages/web/src/pages/recorderScreen/index.module.scss
- packages/web/src/pages/shotScreen/index.tsx
> feat: 增加通知

- .github/workflows/build.yml
- packages/desktop/electron-builder.json5
> feat: 自动打包

- packages/desktop/electron-builder.json5
- packages/desktop/package.json
- packages/web/src/components/recorderAudio/WaveSurferPlayer.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/pages/recorderFullScreen/index.tsx
- packages/web/src/pages/shotScreen/index.tsx
> perf: 优化保存逻辑

- packages/desktop/electron/main/constant.ts
- packages/desktop/electron/main/index.ts
- packages/desktop/electron/main/notification.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/web/src/components/recorderScreen/Camera.tsx
- packages/web/src/components/recorderScreen/FullScreen.tsx
- packages/web/src/components/recorderScreen/MicMuteRecorder.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/components/recorderScreen/ShotScreen.tsx
- packages/web/src/components/recorderScreen/SoundMuteRecorder.tsx
- packages/web/src/pages/index.scss
- packages/web/src/pages/recorderFullScreen/index.tsx
- packages/web/src/pages/recorderScreen/index.module.scss
> fix: 录屏截图 bug

- README.md
- README.zh-CN.md
> docs: add vue-implemented link

- packages/desktop/electron/win/viewAudioWin.ts
- packages/web/public/js/vudio.js
- packages/web/src/pages/viewAudio.html
- packages/web/src/pages/viewAudio/index.module.scss
- packages/web/src/pages/viewAudio/index.tsx
- packages/web/src/vite-env.d.ts
> perf: 修改播放音乐

- packages/desktop/electron/main/ipcMain.ts
- packages/web/src/i18n/locales/zh-CN.json
- packages/web/src/pages/viewImage/index.tsx
> fix: 打开图片文件夹 bug

- packages/recorder/package.json
- packages/screenshot/package.json
- packages/screenshot/src/Screenshots/operations/Brush/draw.ts
- packages/timer/package.json
- packages/web/package.json
> perf: 修改截图画笔有黑线、升级vite

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/editImageWin.ts
- packages/desktop/electron/win/shotScreenWin.ts
- packages/web/src/pages/editImage/index.tsx
- packages/web/src/pages/shotScreen/index.module.scss
- packages/web/src/pages/shotScreen/index.tsx
- packages/web/src/util/file.ts
> feat: 修改截图保存方法

- README.md
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/recorderAudioWin.ts
- packages/desktop/electron/win/viewAudioWin.ts
- packages/web/src/components/recorderAudio/WaveSurferPlayer.tsx
- packages/web/src/pages/recorderAudio/index.module.scss
- packages/web/src/pages/shotScreen/index.tsx
> feat: 修改录音保存方法

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/recorderAudioWin.ts
- packages/desktop/electron/win/recorderScreenWin.ts
- packages/web/src/components/recorderAudio/WaveSurferPlayer.tsx
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
> feat: 修改录屏保存方法

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/recorderFullScreenWin.ts
- packages/web/src/pages/recorderFullScreen/index.tsx
> feat: 修改录全屏保存方法

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/recorderVideoWin.ts
- packages/web/src/components/recorderScreen/SelectMedia.tsx
- packages/web/src/pages/recorderVideo/index.tsx
> feat: 修改录像保存方法

- packages/desktop/electron-builder.json5
- packages/desktop/electron/main/constant.ts
- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/recordsWin.ts
- packages/web/src/components/setting/basicSetting.tsx
> fix: 无法打开保存文件夹

- packages/desktop/electron/win/recorderVideoWin.ts
- packages/web/src/components/recorderScreen/ScreenRecorder.tsx
- packages/web/src/components/records/RecordsContent.tsx
- packages/web/src/i18n/locales/de-DE.json
- packages/web/src/i18n/locales/en-US.json
- packages/web/src/i18n/locales/zh-CN.json
> fix: gif记录预览bug

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/recorderVideoWin.ts
- packages/desktop/electron/win/recordsWin.ts
- packages/desktop/package.json
- packages/web/src/components/records/RecordsContent.tsx
> fix: 记录文件不存在bug

- packages/desktop/package.json
- packages/web/src/components/card/editGifCard.tsx
- packages/web/src/components/card/editImageCard.tsx
- packages/web/src/components/card/pinImageCard.tsx
- packages/web/src/components/card/recordAudioCard.tsx
- packages/web/src/components/card/recordCanvasCard.tsx
- packages/web/src/components/card/recordScreenCard.tsx
- packages/web/src/components/card/recordVideoCard.tsx
- packages/web/src/components/card/scanImageCard.tsx
- packages/web/src/components/card/searchImageCard.tsx
- packages/web/src/components/card/shotScreenCard.tsx
- packages/web/src/components/card/spliceImageCard.tsx
- packages/web/src/components/card/videoConverterCard.tsx
- packages/web/src/components/card/viewAudioCard.tsx
- packages/web/src/components/card/viewImageCard.tsx
- packages/web/src/components/card/viewVideoCard.tsx
- packages/web/src/components/setting/userSetting.tsx
- packages/web/src/pages/home/index.module.scss
- packages/web/src/pages/home/index.tsx
> perf: 修改首页样式

- packages/desktop/electron/win/pinImageWin.ts
- packages/web/src/components/common/header/index.tsx
- packages/web/src/components/common/winBar/index.module.scss
> fix: 贴图显示bug

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/viewImageWin.ts
- packages/web/package.json
- packages/web/src/pages/home/index.module.scss
- packages/web/src/pages/home/index.tsx
> perf: 预览图片多窗口

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/win/viewVideoWin.ts
- packages/web/src/components/card/viewVideoCard.tsx
> feat: 预览视频多窗口

- packages/web/src/components/card/recordScreenCard.tsx
- packages/web/src/components/card/viewImageCard.tsx
- packages/web/src/pages/home/index.tsx
> perf: 优化主页功能

- packages/web/src/components/card/pinImageCard.tsx
- packages/web/src/components/card/scanImageCard.tsx
- packages/web/src/components/card/searchImageCard.tsx
- packages/web/src/components/card/spliceImageCard.tsx
- packages/web/src/components/card/videoConverterCard.tsx
- packages/web/src/i18n/locales/de-DE.json
- packages/web/src/i18n/locales/en-US.json
- packages/web/src/i18n/locales/zh-CN.json
- packages/web/src/pages/home/index.tsx
> fix: 修改主页国际化 bug

- packages/web/src/components/setting/basicSetting.tsx
- packages/web/src/components/setting/shortcutSetting.tsx
- packages/web/src/components/setting/userSetting.tsx
- packages/web/src/i18n/locales/de-DE.json
- packages/web/src/i18n/locales/en-US.json
- packages/web/src/i18n/locales/zh-CN.json
- packages/web/src/pages/pinImage.html
- packages/web/src/pages/pinVideo.html
- packages/web/src/pages/recorderAudio.html
- packages/web/src/pages/recorderFullScreen.html
- packages/web/src/pages/recorderScreen.html
- packages/web/src/pages/recorderVideo.html
- packages/web/src/pages/records.html
- packages/web/src/pages/setting.html
- packages/web/src/pages/shotScreen.html
- packages/web/src/pages/spliceImage.html
- packages/web/src/pages/videoConverter.html
- packages/web/src/pages/viewAudio.html
- packages/web/src/pages/viewImage.html
- packages/web/src/pages/viewVideo.html
> fix: 修改设置页国际化 bug

- README.md
- packages/web/src/components/upload/UploadImg.tsx
- packages/web/src/i18n/locales/de-DE.json
- packages/web/src/i18n/locales/en-US.json
- packages/web/src/i18n/locales/zh-CN.json
- packages/web/src/pages/shotScreen/index.tsx
> fix: 修改截图页国际化 bug

- packages/web/src/components/editImg/index.tsx
- packages/web/src/i18n/locales/de-DE.json
- packages/web/src/i18n/locales/en-US.json
- packages/web/src/i18n/locales/zh-CN.json
- packages/web/src/pages/canvas.html
- packages/web/src/pages/clipScreen.html
- packages/web/src/pages/editGif.html
- packages/web/src/pages/editImage.html
> fix: 修改编辑图片页国际化 bug

- packages/web/src/components/common/winBar/index.tsx
- packages/web/src/i18n/locales/de-DE.json
- packages/web/src/i18n/locales/en-US.json
- packages/web/src/i18n/locales/zh-CN.json
> fix: 修改国际化 bug

- packages/desktop/electron/main/utils.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/web/src/pages/viewImage/index.tsx
> feat: 预览图片列表

- packages/desktop/electron/main/ipcMain.ts
- packages/desktop/electron/main/utils.ts
- packages/desktop/electron/preload/electronAPI.ts
- packages/desktop/electron/win/viewImageWin.ts
- packages/desktop/electron/win/viewVideoWin.ts
- packages/web/src/pages/viewImage/index.tsx
- packages/web/src/pages/viewVideo/index.tsx
> feat: 预览视频列表
